apiVersion: v1
kind: Service
metadata:
  name: swimmingms
spec:
  type: NodePort
  selector:
    name: swimmer-app
  ports:
  - port: 80
    nodePort: 30002
    targetPort: 80
    name: unsecure
  - port: 443
    nodePort: 30003
    targetPort: 443
    name: secure